CREATE TABLE "Activity_Logs" (
  "log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_id" bigint,
  "owner_id" bigint,
  "user_type" text,
  "action" text,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "Admins" (
  "admin_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullname" text,
  "email" text UNIQUE,
  "username" text UNIQUE,
  "password" text,
  "role" text,
  "status" text,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "Owners" (
  "owner_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullname" text,
  "email" text UNIQUE,
  "username" text UNIQUE,
  "password" text,
  "phone_number" varchar,
  "business_name" text,
  "business_address" text,
  "status" varchar,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "Document Categories" (
  "category_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" text,
  "description" text,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "Form Field Groups" (
  "group_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_name" text,
  "group_order" smallint,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "Document Forms" (
  "form_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" bigint,
  "field_name" text,
  "field_type" text,
  "is_required" boolean,
  "field_order" smallint,
  "placeholder" text,
  "default_value" text,
  "group_id" bigint,
  "validation_rule" text,
  "field_width" smallint,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "Documents" (
  "document_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" bigint,
  "document_name" text,
  "document_path" text,
  "description" text,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "Assigned Roles" (
  "assignment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" bigint,
  "admin_id" bigint,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "Requests" (
  "request_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" bigint,
  "tracking_code" text UNIQUE,
  "status" text,
  "date_requested" timestamptz DEFAULT (now()),
  "date_release" date,
  "processed_by" bigint,
  "remarks" text,
  "payment_required" boolean,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "Payments" (
  "payment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" bigint,
  "reference_number" varchar,
  "amount" double,
  "status" text,
  "payment_type" text,
  "description" text,
  "payment_method" text,
  "payment_date" timestamptz,
  "receipt_number" text UNIQUE,
  "processed_by" bigint,
  "remarks" text,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz
);

CREATE TABLE "Notifications" (
  "notification_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_id" int,
  "owner_id" int,
  "type" varchar,
  "subject" varchar,
  "message" text,
  "retry_count" int,
  "read_at" timestamptz,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Login Audits" (
  "audit_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_id" bigint,
  "owner_id" bigint,
  "user_type" text,
  "status" text,
  "login_datetime" timestamptz DEFAULT (now())
);

CREATE TABLE "Request Form Data" (
  "data_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" bigint,
  "form_id" bigint,
  "field_value" text,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "Request Attachments" (
  "attachment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" bigint,
  "file_name" text,
  "file_path" text,
  "remarks" text,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "Form Field Options" (
  "option_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "form_id" bigint,
  "option_value" text,
  "option_order" smallint,
  "created_at" timestamptz DEFAULT (now())
);

ALTER TABLE "Assigned Roles" ADD FOREIGN KEY ("admin_id") REFERENCES "Admins" ("admin_id");

ALTER TABLE "Assigned Roles" ADD FOREIGN KEY ("category_id") REFERENCES "Document Categories" ("category_id");

ALTER TABLE "Document Forms" ADD FOREIGN KEY ("category_id") REFERENCES "Document Categories" ("category_id");

ALTER TABLE "Document Forms" ADD FOREIGN KEY ("group_id") REFERENCES "Form Field Groups" ("group_id");

ALTER TABLE "Documents" ADD FOREIGN KEY ("category_id") REFERENCES "Document Categories" ("category_id");

ALTER TABLE "Requests" ADD FOREIGN KEY ("owner_id") REFERENCES "Owners" ("owner_id");

ALTER TABLE "Requests" ADD FOREIGN KEY ("processed_by") REFERENCES "Admins" ("admin_id");

ALTER TABLE "Payments" ADD FOREIGN KEY ("request_id") REFERENCES "Requests" ("request_id");

ALTER TABLE "Payments" ADD FOREIGN KEY ("processed_by") REFERENCES "Admins" ("admin_id");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("admin_id") REFERENCES "Admins" ("admin_id");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("owner_id") REFERENCES "Owners" ("owner_id");

ALTER TABLE "Login Audits" ADD FOREIGN KEY ("admin_id") REFERENCES "Admins" ("admin_id");

ALTER TABLE "Login Audits" ADD FOREIGN KEY ("owner_id") REFERENCES "Owners" ("owner_id");

ALTER TABLE "Request Form Data" ADD FOREIGN KEY ("request_id") REFERENCES "Requests" ("request_id");

ALTER TABLE "Request Form Data" ADD FOREIGN KEY ("form_id") REFERENCES "Document Forms" ("form_id");

ALTER TABLE "Request Attachments" ADD FOREIGN KEY ("request_id") REFERENCES "Requests" ("request_id");

ALTER TABLE "Form Field Options" ADD FOREIGN KEY ("form_id") REFERENCES "Document Forms" ("form_id");

ALTER TABLE "Activity_Logs" ADD FOREIGN KEY ("admin_id") REFERENCES "Admins" ("admin_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Activity_Logs" ADD FOREIGN KEY ("owner_id") REFERENCES "Owners" ("owner_id") ON DELETE CASCADE ON UPDATE CASCADE;
